services:
  yt-dlp-api:
    build: .
    container_name: yt-dlp-api
    ports:
      - "30191:8191"
    environment:
      - SONARR_URL=http://192.168.216.10:30113
      - SONARR_API_KEY=${SONARR_API_KEY}
      - DOWNLOAD_DIR=/downloads/yt-dlp
      - SONARR_DOWNLOAD_DIR=/downloads/complete/yt-dlp
    volumes:
      - /mnt/nexus/downloads/complete:/downloads
      - /mnt/nexus/media:/media
    restart: unless-stopped
