services:
  yt-dlp-api:
    build: .
    container_name: yt-dlp-api
    ports:
      - "30191:8191"
    environment:
      - SONARR_URL=http://192.168.216.10:30113
      - SONARR_API_KEY=${SONARR_API_KEY}
      - SONARR_TAG=tvb
    volumes:
      - /mnt/nexus/media/tv:/tv
      - /mnt/nexus/downloads:/downloads
    restart: unless-stopped
